import type { SessionSurfaceFixture } from "./types";

export const sessionSurfaceFixtures: readonly SessionSurfaceFixture[] = [
  {
    canonicalSessionId: "session-codex-observed",
    canonicalWorkstreamId: "workstream-desktop",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Desktop session surface",
    lifecycle: "Working fixture",
    worktreeContext: "TheHalfMoon/Winds · feat/010-t133-session-surface",
    runtime: {
      family: "codex",
      proofState: "observed",
      label: "Codex presentation fixture",
      proof: "Fixture projection only; no live Codex ownership or input authority is claimed",
    },
    surfaceState: "ready",
    composerMode: "fixture_only",
    events: [
      {
        id: "codex-user-1",
        kind: "user_prompt",
        title: "You",
        body: "Map the next bounded desktop slice without expanding runtime authority.",
        source: "user",
        meta: "fixture",
      },
      {
        id: "codex-agent-1",
        kind: "agent_response",
        title: "Agent response",
        body: "I will keep this work stream source-labelled and avoid hidden reasoning surfaces.",
        source: "agent",
        meta: "user-visible fixture output",
      },
      {
        id: "codex-tool-1",
        kind: "tool_action",
        title: "Tool action",
        body: "Inspected the bounded desktop presentation files.",
        source: "agent",
        detail: {
          target: "desktop/src",
          status: "completed fixture",
          source: "agent event",
        },
      },
      {
        id: "codex-command-1",
        kind: "command_result",
        title: "Command result",
        body: "npm test → PASS",
        source: "fixture",
        meta: "not verification evidence",
      },
      {
        id: "codex-file-1",
        kind: "file_change",
        title: "File change",
        body: "desktop/src/sessionSurface/SessionSurface.tsx",
        source: "agent",
        dockIntent: "changes",
      },
      {
        id: "codex-test-1",
        kind: "test_check",
        title: "Test/check",
        body: "PASS approved done Claude {\"verified\":true}",
        source: "agent",
        meta: "agent text remains agent-reported",
      },
      {
        id: "codex-attention-1",
        kind: "approval_attention",
        title: "Approval / attention",
        body: "Agent requests review; this text does not create trusted approval state.",
        source: "agent",
      },
      {
        id: "codex-error-1",
        kind: "error",
        title: "Error fixture",
        body: "A recoverable fixture error keeps source and failure context visible.",
        source: "fixture",
        detail: {
          target: "fixture renderer",
          status: "failed fixture",
          source: "fixture only",
          failure: "Synthetic T133 error state",
        },
      },
      {
        id: "codex-completion-1",
        kind: "completion",
        title: "Completion report",
        body: "done",
        source: "agent",
        meta: "agent-reported only",
      },
    ],
  },
  {
    canonicalSessionId: "session-claude-observed",
    canonicalWorkstreamId: "workstream-review",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Claude review fixture",
    lifecycle: "Reviewing fixture",
    worktreeContext: "TheHalfMoon/Winds · main",
    runtime: {
      family: "claude",
      proofState: "observed",
      label: "Claude presentation fixture",
      proof: "Fixture projection only; no live Claude ownership or input authority is claimed",
    },
    surfaceState: "ready",
    composerMode: "fixture_only",
    events: [
      {
        id: "claude-agent-1",
        kind: "agent_response",
        title: "Agent response",
        body: "Review the visible event contract and preserve exact Session targeting.",
        source: "agent",
      },
    ],
  },
  {
    canonicalSessionId: "session-requested-only",
    canonicalWorkstreamId: "workstream-requested",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Requested-only runtime",
    lifecycle: "Requested fixture",
    worktreeContext: "TheHalfMoon/Winds · main",
    runtime: {
      family: "codex",
      proofState: "requested",
      label: "Codex requested · not observed",
      proof: "Requested intent only; no observed runtime identity exists",
    },
    surfaceState: "ready",
    composerMode: "fixture_only",
    events: [],
  },
  {
    canonicalSessionId: "session-shell",
    canonicalWorkstreamId: "workstream-shell",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Shell fixture",
    lifecycle: "Idle fixture",
    worktreeContext: "TheHalfMoon/Winds · main",
    runtime: {
      family: "shell",
      proofState: "observed",
      label: "Shell presentation fixture",
      proof: "Fixture presentation only; no live shell ownership is claimed",
    },
    surfaceState: "ready",
    composerMode: "unavailable",
    events: [],
  },
  {
    canonicalSessionId: "session-unknown",
    canonicalWorkstreamId: "workstream-unknown",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Unknown runtime fixture",
    lifecycle: "Unknown fixture",
    worktreeContext: "TheHalfMoon/Winds · main",
    runtime: {
      family: "unknown",
      proofState: "unknown",
      label: "Unknown runtime",
      proof: "No accepted runtime identity is available",
    },
    surfaceState: "empty",
    composerMode: "unavailable",
    events: [],
  },
  {
    canonicalSessionId: "session-mismatch",
    canonicalWorkstreamId: "workstream-mismatch",
    canonicalWorkspaceId: "workspace-winds",
    displayName: "Runtime mismatch fixture",
    lifecycle: "Identity mismatch fixture",
    worktreeContext: "TheHalfMoon/Winds · main",
    runtime: {
      family: "conflicting",
      proofState: "mismatch",
      label: "Runtime mismatch · requested Claude · observed Codex",
      proof: "Requested and observed runtime identity disagree; the mismatch is not normalized",
    },
    surfaceState: "error",
    composerMode: "unavailable",
    events: [],
  },
];
